apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rabbitmq
  namespace: rabbitmq-system
spec:
  type: oci
  interval: 60m0s
  url: oci://registry-1.docker.io/bitnamicharts
