# See https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      version: "4.7.x"
