# This config applies recursively to all sub-directories.

# Multiple directories can use separate SOPS configs.

# Contributors using the sops CLI to create and encrypt files won’t have to worry
# about specifying the proper key for the target cluster or namespace.
# Therefore, they can just encrypt files with `sops -e file.yaml`

# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - path_regex: .*/crossplane/.*.yaml
    encrypted_regex: ^(data|stringData)$
    # Private key should be in ./sops.keys
    age: age1v6q8sylunaq9m08rwxq702enmmh9lama7sp47vkcw3z8wm74z39q846s3y
  - path_regex: .*/staging/.*.yaml
    encrypted_regex: ^(data|stringData)$
    # Private key should be in ./sops.keys
    age: age1qvesyd4zyqs5p40n8gr2ngjvsg6surf9e37h3xv7rm7m5lsgz5jsetg3ql
  - path_regex: .*/production/.*.yaml
    encrypted_regex: ^(data|stringData)$
    # Private key should be in ./sops.keys
    age: age1g2wjea9r33l6w0kr6g49yh2tgz3mx6l6dt9a8umaf6fzdkgfsemqmrzxxg
