apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: resources
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: providers
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cloud/resources/base
  prune: true
  wait: true
