apiVersion: v1
kind: Secret
metadata:
  name: fastapi-example-docker
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:Eab/kCHKlh5DDUdPcWyu46X2l4nQ5dSIP93iPqf/aTL846ki4l9PFfqfqioVGqDSBqn44hucmE2jJ60QMIwLsSFKW0SsvOOjNWARfbb1eoU+VNJ/naX+84zzlTmW6k/BdVmgc2BDxwSOoPf/+5LNOntEjW52FeLndpgn8UVKXzp9R4C4UDKhDyCAW4u8wDxdioOYowS/PHCnA+6DWRevSbxc4rB2+1v7nMDCfrPUW1c6v+v6+g+Gpct1HZSmPQSGFVGpaz8lqJjJDG4W+fvUX3mQAi8E2a/ck/60gckXCUz+0orfeKuN650fFe205TtbaXOjp1pR+zmRmR7uom/IqZI5n4cFQd3gBLGvPRv4Y1lRAom9vVblR5/krbaG7Uy8wzqR94aNNaEpfIvZ/pKlzZPdLg//fyilZtY++C2X8SQ6CTCzUQRNrW4wOTkI2cLu8QFVnbH/Ou+iwN7fTA==,iv:dt5LRhg2JBFkjVT8OHjMiuL/BH/VFTC4V5567ZAxNzQ=,tag:5hcZjnR+tTGk6jMoN3mjpw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qvesyd4zyqs5p40n8gr2ngjvsg6surf9e37h3xv7rm7m5lsgz5jsetg3ql
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZVRqRG1wK3dJdThmSW55
        dHVnUHdrVXlwYkV3VXJZWWNzSlVMZzFQVFd3ClFIa0FBaitWb1Q2aUpEaDlySThY
        dDZ0d1ZoYzJEQmN2K2tNUDlzdnFXVDQKLS0tICt5aGJMdEZuZUhadHdHbHMyMjAy
        UG9nQ1VLSUczNVBYT0orbnB3ektTTzQKrlYViO5r0HxjXT1K4WD7VzKSg46Q7hbt
        9zI447Wve/A8zN1VN76tTQaYYOiMb046l9zz5hgHGv0ytoqTRMdFBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-07-18T10:33:12Z"
  mac: ENC[AES256_GCM,data:KKM2jy//8QZ/ggsv1BrlrNiwW6G+GyChR2NabQRAJVyC3gcuResThsCse5PNhEUY87kMnGwnWp6CXy01xK0sbeC2dBk0iEO4QkS5Xu+UFnjbzTdir1Axuit27RBMJAmDxxJAkZkC6dkXV21Hky7+FzNmnqwz7uO8IFriQZIRx8c=,iv:gmoa2XeZskQ38I7fpXurUXDnftUfFN91QpeLPZeLTTo=,tag:gVhHUWJwyTemSY+xHJGZ3A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
