apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:u6X120gIIyt5Fu685i01GFL8C9NHxvMAb3s4+eWsegSu0OD5l087Ne9+mTU82Shsd8Wcj5wjxbUBn6gU7ie+gUe/pT00m+lqw5TYaKdG5qyYjvxG8FANdULwALPFaJ08dnZ5rEqslyebwn76KEXfizZUGSxC7sMqhVmj4ozsh7jkJquBH33kMNmlZ8dF03bSzL9FKS/pagcyeeMc7Zr5+e2J/Wt1md6aEexgAK/tWtpF+NCbATBRKxDPY9uxGiKOeiaixSablT56OPDfKspKFTDaUZPwGoOvZdJMJImtQmgNK5iJRwZ99nk+rApSOKI4SGBSvkBEvMGa7muQYzvfjUZrJT38+RsKqGumy32JdMuSEo5uhxS1tVjdLzB5zD6zxdro1lgUI6NP3BF19NjnqBdXMYHJfjWpMDiY+77XZiL0jeHfXbnpVC7K79FWxPP00otky6+C/Z/kZwGadBflrbnH+bIzJGyGA2jWvUGnXxBQ9rYmI3fyYbHSsC3fqiHc+AOemr0i1kASUPUXlexaV9ujwwW1kwQQ,iv:1swxCmN3DELNplZMxgVP++TUafSK7dlq0hD/nhrTybU=,tag:gFyeLIcBXV27i/m0sOh2yw==,type:str]
kind: Secret
metadata:
  name: fastapi-example-docker
  namespace: fastapi-example
type: kubernetes.io/dockerconfigjson
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qvesyd4zyqs5p40n8gr2ngjvsg6surf9e37h3xv7rm7m5lsgz5jsetg3ql
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ME1LYW1ydSt2NWNWTkpI
        bEZOV3FWSDZDN3BjUWU4QU9hVjlaelZ5dEEwCmhHQ2VNNExxQUM0dllTWDEySk5y
        cUpvd1ZSNjZQNDNBbTRQQTlHemh6TFUKLS0tIGJXVS9YMW9YMklqVzM1dW9zMTds
        V0NIZjBEa0FnY1ExY0NpVTd2NEd0eE0Kj52LX4i1guJwQ9MAEZoLj7nfXvoJrBEI
        Ae0YIzFSw4vWgNFp0f8YMV9aVp6dXMm6u+m/bFvZGUCveLYy5MPA3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-07-18T11:38:13Z"
  mac: ENC[AES256_GCM,data:TY5jJKxdhjiJtn2NQAUmmJSSgSmvncCS3/L7D3R+8IWc3bzzxZOU23AnHnKiKRcTZCd2T37qLJkC3JUUbnD9SyQ3RT3zL/Muzfd79EX/JSCFAMsNQqEVljIkRHipLjlq6AOxTqf0RA7TvRxKsA1JzFySHQfuBcIN2qqkJd8aglM=,iv:L73PGpiAKr9AHdoNu8cnCP+suxQLDSuAUjoPvC/aRfw=,tag:lgBZLQEsIMNrn8GXMpuLbg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
