---
apiVersion: v1
kind: Namespace
metadata:
  name: gcp-buckets
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-example
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
