apiVersion: v1
kind: Secret
metadata:
  name: fastapi-example-docker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:XhlhwhwpBpiEkcOXuZEr0l4+tnO9JRhenAln3ZCGCZaembUx1Od9zbnWwN6HB96fLBvN+UPkOPNsWqcd1ZD52/7DZBmLBngpp6Jp/k5NE+uR2a2xJgj2hZQPhMobCq7YFhLkuLvZCSmJn3kEccqeQiIuGM+8slrYuEr9sJBciJ+iqbGvyYnyj3LnlQiVaOxEJgR04I3Uc776PuTXRePHWpxQxnkczEYO7Y5AKKrh1mfuk/oAQBC7yaFO4MS79j/CQGfp/+oQCBWfqhlsdBogUh4bGJaJKrjA5mtq7REDXtHDT3jQXssutc8Mr+ggkxzNSoH9qwbN0mv3bvrhrODmEYuENs9Sqnd2fBMk9LJ/5YOxTd6+4F5UooBqOx89QJjxdRIN0wlTusAG0vQl8Ux1e5o4haq+hQMLlrKsF35yS27l1qNNSvUNDhJ9bTwM/umHSepVmw==,iv:E8r6gs+HWPWNJH7D1CQ4ZvYLeS45KXlkq3yjZtGRK6o=,tag:AgQuKl0giKxbiS1ScOCuIw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g2wjea9r33l6w0kr6g49yh2tgz3mx6l6dt9a8umaf6fzdkgfsemqmrzxxg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYXkzRFoxZHZxb3RmVUZG
        TS9KQ0tLZWgvT2xsNTh0SlFnNDY2MWtiR3hZCmMwMjI4Y280L05hdzdSc00wb3VW
        ejRxSmYzK2EzYW42c2YvWE5oZVo3b00KLS0tIDA4SVhTcGlkZkQzS3JkeXo0VElR
        elVrb0JGRCtHaDdTYXBJVjRIL2ZYOGsKB9/VPxc0KpYPzaH3VL5lTD3xm6xWvC14
        thPCF4i554pI9m0OMqlhedYpqc4ZK7RXEuEYXmXcYHFkiZ94iLlQJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-07-18T10:48:28Z"
  mac: ENC[AES256_GCM,data:aWUsHK85K64Mh5nudJkQ/slRHzIJuWocDmqFh1I9B29Yj6GRTVUECTs3U9LJRp09RuV0UrkNHEwykzs3wrmDWxoIZDdGX4MMYa6iC0DCb8e6N3FhVu/YIAUHCW/OlIqJfN6FdvYYSwj9cX95pdA32FHioVIyNpNM7YSTpszP7WY=,iv:7/z0P/Ym5303KpKJk4RYJGHvTRP2GCWiID9VSizR2go=,tag:UXnlLh7kZ60Fw+REY4EjKQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
