apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastapi-example
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: fastapi-example
  decryption:
    provider: sops
    secretRef:
      name: sops-age
