apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fastapi-example
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/darioblanco/fastapi-example
  ref:
    branch: main
  secretRef:
    name: fastapi-example
