apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: fastapi-example
  namespace: flux-system
spec:
  image: ghcr.io/darioblanco/fastapi-example
  interval: 1h
  secretRef:
    name: github-docker
