apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastapi-example
  namespace: fastapi-example
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: fastapi-example
  validation: client
