apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/weave-gitops
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
secretGenerator:
  - name: weave-gitops-secrets
    files:
      - values.yaml=secret-values.enc.yaml
