# See https://github.com/weaveworks/weave-gitops/tree/main/charts/gitops-server
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  chart:
    spec:
      version: "*"
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  valuesFrom:
    - kind: Secret
      name: weave-gitops
