apiVersion: v1
kind: Secret
metadata:
  name: weave-gitops
  annotations:
    kubernetes.io/service-account.name: sa-name
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:JNED8ggpU3APNIk6/9XejdbAQj1kMngtHzDUkvoj2jNCmU/WrRTHnmrCygcTYYEBmEqgtaEONWe2GoUtO68Bvi1zdtcAwb6myLuLmKY=,iv:KVu/IKlabPXtJNAEULPWCTTEUYU6UeIXOcqqbJonXMo=,tag:kNYikX3AHZzV81mZAk35AA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qvesyd4zyqs5p40n8gr2ngjvsg6surf9e37h3xv7rm7m5lsgz5jsetg3ql
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQy9WdVJkZS9zeUR2cjA0
        Q1FGVjNMOG9kajJiZ3Vqa1VCcE1tVjZMd0FvCmJpbEhGN2FrclBiU0h6MFRJdG9X
        emUyaC8vTk4razNZd3IyR2FKWmJickkKLS0tIGNlRmlLRHU5SUQxV0YwV0tHamky
        VmpmTlhEVU81ekUrZktjSXRaQWlaUmcKYJGkUo9jwB0xUGOFqZOSa9Zw3uFWr/aA
        PX+v1HeWTwGzta3XHDozEh17uiJOMrIclWFIwGMsZ9hyKKBVb2sYDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-07-17T22:52:35Z"
  mac: ENC[AES256_GCM,data:GITn01cd5939uLjeb+rB9uuSGRQ/r8tgcr9Aj7xScEegAUTmtB8CbogAaiTKHRb95y3k+LUq0Z6d7J42RZR2NBG4S0p/OdVNy0CczgSmKeQ1LeBfugiPqQq+8Xj8wadvrx+EHvHdkNp8WpKeLnTJImgu3Ot8+CEFQcwhV0qdBpI=,iv:t1DBmtyFIoKr7teXmyvVMEbwiXWjXhSL1visqUvYvlE=,tag:Ce0Ak5fIDA8mzMLsYf7ozQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
