apiVersion: v1
kind: Secret
metadata:
  name: gcp-secret
  namespace: crossplane-system
type: Opaque
data:
  credentials: <some_base64_encoded_value_here> # gcp-credentials.json file content goes here in base64 format
